#!/bin/bash
find* -type d | wc -l
[master 2c23ee7] Don't just count your directories, make your directories count
 1 file changed, 2 insertions(+)
 create mode 100755 0x02-shell_redirections/11-directories
